#!/bin/bash

alias gst='git status'
alias gcm="git checkout master"
alias gcb="git checkout -b"
alias gco="git checkout"
alias gcor="git checkout --recurse-submodules"
alias ggpush="git push origin HEAD"
alias ggp=ggpush
alias ggpull="git pull origin HEAD"
alias ggl=ggpull
alias gcl="git clone --recurse-submodules"
alias empty_commit="git commit --allow-empty -m 'Empty commit'"

