[font]
size = 14

[font.bold]
family = "FiraCode Nerd Font Propo"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Propo"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Propo"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
decorations = "Full"
opacity = 0.8
blur = true

[scrolling]
history = 10000
multiplier = 3

[shell]
program = '/usr/local/bin/fish'
args = ['--login']

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '0x002221'
foreground = '0xe6f8f8'

[colors.normal]
black =   '0x002221'
red =  '0xea3431'
green =   '0x00b6b6'
yellow =  '0xf8b017'
blue = '0x4894fd'
magenta ='0xe01dca'
cyan =   '0x1ab2ad'
white =   '0x99dddb'


[colors.bright]
black =   '0x006562'
red =  '0xea3431'
green =  '0x00b6b6'
yellow =  '0xf8b017'
blue = '0x4894fd'
magenta = '0xe01dca'
cyan ='0x1ab2ad'
white =  '0xe6f6f6'

[keyboard]
bindings = [
  { key = "Escape", mods = "Shift", action = "ToggleViMode" },
  { key = "q", mode = "Vi", action = "ToggleViMode" },
]
